### ISSUE TITLE
Please bring this extension to Firefox

### ISSUE THREAD

**Issue by logicalup** [haoala/MouseHunt-Horn-Timer#1]
People (including myself) are enjoying your extension on Chrome, and want to see it on FF too. Can you please update your extension to work with FF too?
As far as I saw there are some chrome-only methods being used, jquery needs to be updated from 1.x to newer, and maybe icon name or reference to it updated.

**Comment by haoala** [comment]
Unfortunately, I no longer play MouseHunt, so I haven't touched this in years. Feel free to take the code and port it over to Firefox.
